### ISSUE TITLE
Cyclical dependency issue

### ISSUE THREAD

**Issue by dekm** [unigrid-project/cosmos-ugdmint#4]
There is a cyclical dependcy when compiling the daemon with ignite in this module.

**Comment by dekm** [comment]
This issue still exsits and was only being caught in a dot visualizer.

```
if err := depinject.InjectDebug(
		depinject.FileVisualizer("/home/evan/work/cosmos-daemon/output.dot"),
		depinject.Configs(
			app.AppConfig(),
			depinject.Supply(
				log.NewNopLogger(),
			),
			depinject.Provide(
				ProvideClientContext,
				ProvideKeyring,
			),
		),
		&txConfigOpts,
		&autoCliOpts,
		&moduleBasicManager,
		&clientCtx,
	); err != nil {
		panic(err)
	}
```

```
 Panic: cyclic dependency: github.com/unigrid-project/cosmos-ugdmint/x/ugdmint/module.ProvideModule -> github.com/unigrid-project/cosmos-ugdmint/x/ugdmint/module.ProvideModule
                                                                                                                                                                              
goroutine 1 [running]:                                                                                                                                                        
github.com/unigrid-project/pax/cmd/paxd/cmd.NewRootCmd()                                                                                                                      
        /home/evan/work/cosmos-daemon/cmd/paxd/cmd/root.go:64 +0xbf2                                                                                                                  
main.main()                                                                                                                                                                   
        /home/evan/work/cosmos-daemon/cmd/paxd/main.go:14 +0x1f                                                                                                                       
: exit status 2 
```

**Comment by dekm** [comment]
Just pushed a branch with the proper BeginBlock added.

https://github.com/unigrid-project/cosmos-ugdmint/tree/eg_fixupdatemerge
